version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g aws-cdk

  pre_build:
    commands:
      - echo Running ESLint...
      - npm run eslint

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling TypeScript...
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Synthesizing CDK...
      - cdk synth
      - echo "Extracting S3 bucket and S3 key..."
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - export AWS_DEFAULT_REGION=$(aws configure get region)
      - export S3_BUCKET=$(jq -r '.Resources.WidgetsWidgetHandler1BC9DB34.Properties.Code.S3Bucket."Fn::Sub"' cdk.out/AwsCdkAppStack.template.json)
      - export S3_BUCKET=${S3_BUCKET/\$\{AWS::AccountId\}/$AWS_ACCOUNT_ID}
      - export S3_BUCKET=${S3_BUCKET/\$\{AWS::Region\}/$AWS_DEFAULT_REGION}
      - export S3_KEY=$(jq -r '.Resources.WidgetsWidgetHandler1BC9DB34.Properties.Code.S3Key' cdk.out/AwsCdkAppStack.template.json)

      - echo "Creating ZIP file..."
      - cd dist/src/widget
      - zip -r $S3_KEY .

      - echo "Uploading ZIP file to S3..."
      - aws s3 cp $S3_KEY s3://$S3_BUCKET/
