version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install

  pre_build:
    commands:
      - echo Running ESLint...
      - npm run eslint

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling TypeScript...
      - npm run build

artifacts:
  files:
    - 'dist/**/*'
    - '**/*'
  discard-paths: yes

